name: Install llvm-msvc
description: Install llvm-msvc

inputs:
  version:
    description: Version to install
    required: false
    default: latest

runs:
  using: composite
  steps:
      - run: |
          $psCommand = 'Start-Process ' + "`"${env:GITHUB_ACTION}`"" + ' -Verb RunAs'
          Start-Process powershell -Verb RunAs -ArgumentList 'Invoke-Expression', $psCommand
        shell: powershell
      
      - id: llvm-msvc-latest_release
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await github.repos.getLatestRelease({
              owner: 'NewWorldComingSoon',
              repo: 'llvm-msvc-build'
            })
            console.log(data.tag_name)
            return data.tag_name
            
      - run: |
          $url = 'https://github.com/NewWorldComingSoon/llvm-msvc-build/releases/download/' + ${{ steps.llvm-msvc-latest_release.outputs.result }} + '/llvm-msvc_X86_64_installer.exe'
          $exe = Join-Path $env:TEMP 'llvm-msvc_X86_64_installer.exe'
          Invoke-WebRequest -Uri $url -OutFile $exe
          Start-Process -FilePath $exe -ArgumentList '/verysilent' -Verb RunAs
        shell: powershell
  
